name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings  # Exit with non-zero status if warnings are emitted

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --verbose
  check-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: cargo check --verbose
      - name: Clippy
        run: cargo clippy --verbose
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Typos Checking
        uses: crate-ci/typos@v1.29.9