name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-13
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Get API Tokens with BWS
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BWS_ACCESS_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            04b9554e-f7af-497b-8095-b28d011e347d > RELEASE_PLZ_TOKEN
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: env2bws
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          token: ${{ env.RELEASE_PLZ_TOKEN }}
          ref: refs/tags/v0.1.2
